torch_optimizer
torch
tensorflow
torchvision
transformers
scipy
matplotlib
torch_baidu_ctc
tensorboardX
python-levenshtein
pandas
PyYAML
pytest
sox
grpcio==1.40.0
gym
jupyter
pillow
sentencepiece
gdown
h5py
librosa
SoundFile
kubernetes